/**
 * TEAM: frontend_infra
 * WATCHERS: AlaRuba
 *
 * @flow strict
 */
import keyMirror from "keymirror";

export type PayloadType<ActionType> = {
  action: ActionType,
  source: string,
};

// TODO(dshah): Replace all uses of the type below with the one above
export type Payload<RecordType> = {
  action: {
    actionType: string,
    record: RecordType,
    changes: $Shape<RecordType>,
  },
  source: string,
};

const PayloadSources = keyMirror({
  ACCESSORIAL: null,
  ACTION_ITEM: null,
  ACTION_ITEM_CALCULATION_JOB: null,
  ADDRESS: null,
  ADDRESS_VERIFICATION: null,
  AFFILIATE: null,
  AIR_OFFERING: null,
  ALERT: null,
  ALLOCATION: null,
  ARRIVAL_NOTICE: null,
  ASSIGNMENT: null,
  AUTH: null,
  BILL: null,
  BILL_OF_LADING: null,
  BOND_SURVEY: null,
  BOOKING: null,
  BOOKING_LINE_ITEM: null,
  BOOKING_TEMPLATE: null,
  CARGO_MANIFEST_QUERY_LOG: null,
  CARRIER: null,
  CARRIER_BOOKING: null,
  CARTAGE_OFFERING: null,
  CHARGE: null,
  CHECKLIST: null,
  CITY: null,
  CLIENT: null,
  COLLABORATING_PARTY: null,
  COMMERCIAL_INVOICE: null,
  COMMERCIAL_INVOICE_LINE_ITEM: null,
  COMPANY: null,
  COMPANY_DATA: null,
  CONSOL: null,
  COMPANY_MERGE: null,
  CONTACT: null,
  CONTAINER: null,
  CORE_CLIENT_MESSAGE: null,
  CUSTOMS_BOND: null,
  DATA_ENTRY: null,
  DATA_ENTRY_SHIPMENT: null,
  DELIVERIES_REPORT: null,
  DELIVERY: null,
  DELIVERY_ORDER: null,
  DESTINATION_OFFERING: null,
  DOCUMENT: null,
  DRAYAGE_OFFERING: null,
  DRIVER: null,
  DRIVER_DUTY_STATUS_LOG: null,
  DUTY_STATUS_VIOLATION: null,
  EMAIL: null,
  EMAIL_LOG: null,
  EVENT: null,
  EXPORT_CUSTOMS_OFFERING: null,
  EXTERNAL_ADDRESS: null,
  FEEDBACK: null,
  FEED_MESSAGE: null,
  FILE_ASSET: null,
  FLOATING_SEGMENT_MARKUP: null,
  FREIGHT_PARTNER: null,
  FULFILLMENT_CENTER: null,
  GEO_BOUND: null,
  GRAPH: null,
  GREENHOUSE: null,
  IMPORTER_SECURITY_FILING: null,
  IMPORT_CUSTOMS_OFFERING: null,
  INBOX: null,
  INSURANCE_OFFERING: null,
  INVOICE: null,
  INVOICES_REPORT: null,
  INVOLVED_PARTY_GROUP: null,
  ITEM_TEMPLATE: null,
  LOAD_FILTERS: null,
  LOCATION: null,
  MODAL: null,
  NETCHB_CREDENTIAL: null,
  NETSUITE_VENDOR: null,
  NETWORK_CONNECTION: null,
  NETWORK_LOCATION: null,
  NOTE: null,
  NOTIFICATION: null,
  NOTIFICATION_PREFERENCE: null,
  NOTIFICATION_TYPE: null,
  OCEAN_FCL_OFFERING: null,
  OCEAN_LCL_OFFERING: null,
  OPPORTUNITY: null,
  ORIGIN_BOOKING_OFFERING: null,
  PARTNER: null,
  PERMISSION: null,
  PORT: null,
  PORT_GROUP: null,
  PRESENCE: null,
  PRODUCT: null,
  PURCHASE_ORDER: null,
  QUOTE: null,
  QUOTE_REQUEST: null,
  QUOTING_INVENTORY: null,
  RATE: null,
  RATE_SHEET: null,
  RATE_SOURCE: null,
  REPORT: null,
  SERVICE_AREA: null,
  SERVICE_ITEM_TEMPLATE: null,
  SERVICE_OFFERING: null,
  SERVICE_OFFERING_SHEET: null,
  SERVICE_STRING: null,
  SHIPMENT: null,
  SHIPMENT_DETAILS: null,
  SHIPMENT_EVENT: null,
  SHIPMENT_MESSAGE: null,
  SHIPMENT_UPDATE: null,
  SIGN_UP_FLOW: null,
  SKU: null,
  SUPPORT_QUESTION: null,
  SWITCH: null,
  TOAST: null,
  TRUCK: null,
  TRUCK_INSPECTION_REPORT: null,
  USER: null,
  VALID_DESTINATION_ROUTE: null,
  VEHICLE_TRIP: null,
  VESSEL: null,
  VIEWPORT: null,
  VOYAGE: null,
  WAREHOUSE: null,
  WAREHOUSE_OFFERING: null,
  WEBHOOK: null,
  SHIPPING_INSTRUCTION: null,
});

export default PayloadSources;
