// flow-typed signature: 883189bb1f92a6c2faef7ba6156b469e
// flow-typed version: <<STUB>>/flux_v2.0.x/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */
type Dispatcher = {
  isDispatching: () => boolean,
  dispatch: (arg: {source: string, action: {}}) => void,
  // For some reason, passing in {} here doesn't work
  register: (func: (payload: Object) => boolean) => string,
  waitFor: (tokens: Array<string>) => void,
};
declare module 'flux' {
  declare module.exports: {
    Dispatcher: () => Dispatcher;
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flux/lib/Dispatcher' {
  declare module.exports: any;
}

declare module 'flux/lib/invariant' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flux/index' {
  declare module.exports: $Exports<'flux'>;
}
declare module 'flux/index.js' {
  declare module.exports: $Exports<'flux'>;
}
declare module 'flux/lib/Dispatcher.js' {
  declare module.exports: $Exports<'flux/lib/Dispatcher'>;
}
declare module 'flux/lib/invariant.js' {
  declare module.exports: $Exports<'flux/lib/invariant'>;
}
