// flow-typed signature: 60d2e8e7a2a73e917edadf56da784a1d
// flow-typed version: <<STUB>>/keymirror_v0.1.x/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keymirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "keymirror" {
  declare module.exports: <O>(obj: O) => $ObjMapi<O, <K>(k: K) => K>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "keymirror/index" {
  declare module.exports: $Exports<"keymirror">;
}
declare module "keymirror/index.js" {
  declare module.exports: $Exports<"keymirror">;
}
