// flow-typed signature: d97aaf7aba1ac503c3553d4883c98fd4
// flow-typed version: <<STUB>>/react-onclickoutside_v^5.3.1/flow_v0.34.0

import React from 'react';

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: <A,B,C>(Class<React.Component<A, B, C>>) => Class<React.Component<A, B, C>>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onclickoutside/test/browser/testit' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/karma.conf' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onclickoutside/index' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/index.js' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/test/browser/testit.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/browser/testit'>;
}
declare module 'react-onclickoutside/test/karma.conf.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/karma.conf'>;
}
declare module 'react-onclickoutside/test/test.js' {
  declare module.exports: $Exports<'react-onclickoutside/test/test'>;
}
