// flow-typed signature: 5e6b6f785cf6d8898cfc1ff4ac69d1e1
// flow-typed version: <<STUB>>/react-infinite_v^0.9.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-infinite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-infinite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-infinite/__tests__/array_infinite_computer_test' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/binary_search_test' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/bottom_upwards_infinite_test' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/constant_infinite_computer_test' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/helpers/renderHelpers' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/infinite_error_test' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/infinite_styles_test' {
  declare module.exports: any;
}

declare module 'react-infinite/__tests__/infinite_test' {
  declare module.exports: any;
}

declare module 'react-infinite/build/computers/arrayInfiniteComputer' {
  declare module.exports: any;
}

declare module 'react-infinite/build/computers/constantInfiniteComputer' {
  declare module.exports: any;
}

declare module 'react-infinite/build/computers/infiniteComputer' {
  declare module.exports: any;
}

declare module 'react-infinite/build/react-infinite' {
  declare module.exports: any;
}

declare module 'react-infinite/build/utils/binaryIndexSearch' {
  declare module.exports: any;
}

declare module 'react-infinite/build/utils/checkProps' {
  declare module.exports: any;
}

declare module 'react-infinite/build/utils/establish-polyfills' {
  declare module.exports: any;
}

declare module 'react-infinite/build/utils/infiniteHelpers' {
  declare module.exports: any;
}

declare module 'react-infinite/build/utils/scaleEnum' {
  declare module.exports: any;
}

declare module 'react-infinite/build/utils/types' {
  declare module.exports: any;
}

declare module 'react-infinite/dist/react-infinite' {
  declare module.exports: any;
}

declare module 'react-infinite/dist/react-infinite.min' {
  declare module.exports: any;
}

declare module 'react-infinite/examples/borderless-window' {
  declare module.exports: any;
}

declare module 'react-infinite/examples/chat' {
  declare module.exports: any;
}

declare module 'react-infinite/examples/index' {
  declare module.exports: any;
}

declare module 'react-infinite/examples/window' {
  declare module.exports: any;
}

declare module 'react-infinite/Gulpfile' {
  declare module.exports: any;
}

declare module 'react-infinite/pipeline/browserify' {
  declare module.exports: any;
}

declare module 'react-infinite/src/computers/arrayInfiniteComputer' {
  declare module.exports: any;
}

declare module 'react-infinite/src/computers/constantInfiniteComputer' {
  declare module.exports: any;
}

declare module 'react-infinite/src/computers/infiniteComputer' {
  declare module.exports: any;
}

declare module 'react-infinite/src/react-infinite' {
  declare module.exports: any;
}

declare module 'react-infinite/src/utils/binaryIndexSearch' {
  declare module.exports: any;
}

declare module 'react-infinite/src/utils/checkProps' {
  declare module.exports: any;
}

declare module 'react-infinite/src/utils/establish-polyfills' {
  declare module.exports: any;
}

declare module 'react-infinite/src/utils/infiniteHelpers' {
  declare module.exports: any;
}

declare module 'react-infinite/src/utils/scaleEnum' {
  declare module.exports: any;
}

declare module 'react-infinite/src/utils/types' {
  declare module.exports: any;
}

declare module 'react-infinite/typelib/component/infinite_computer_types' {
  declare module.exports: any;
}

declare module 'react-infinite/typelib/component/react_infinite_types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-infinite/__tests__/array_infinite_computer_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/array_infinite_computer_test'>;
}
declare module 'react-infinite/__tests__/binary_search_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/binary_search_test'>;
}
declare module 'react-infinite/__tests__/bottom_upwards_infinite_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/bottom_upwards_infinite_test'>;
}
declare module 'react-infinite/__tests__/constant_infinite_computer_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/constant_infinite_computer_test'>;
}
declare module 'react-infinite/__tests__/helpers/renderHelpers.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/helpers/renderHelpers'>;
}
declare module 'react-infinite/__tests__/infinite_error_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/infinite_error_test'>;
}
declare module 'react-infinite/__tests__/infinite_styles_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/infinite_styles_test'>;
}
declare module 'react-infinite/__tests__/infinite_test.js' {
  declare module.exports: $Exports<'react-infinite/__tests__/infinite_test'>;
}
declare module 'react-infinite/build/computers/arrayInfiniteComputer.js' {
  declare module.exports: $Exports<'react-infinite/build/computers/arrayInfiniteComputer'>;
}
declare module 'react-infinite/build/computers/constantInfiniteComputer.js' {
  declare module.exports: $Exports<'react-infinite/build/computers/constantInfiniteComputer'>;
}
declare module 'react-infinite/build/computers/infiniteComputer.js' {
  declare module.exports: $Exports<'react-infinite/build/computers/infiniteComputer'>;
}
declare module 'react-infinite/build/react-infinite.js' {
  declare module.exports: $Exports<'react-infinite/build/react-infinite'>;
}
declare module 'react-infinite/build/utils/binaryIndexSearch.js' {
  declare module.exports: $Exports<'react-infinite/build/utils/binaryIndexSearch'>;
}
declare module 'react-infinite/build/utils/checkProps.js' {
  declare module.exports: $Exports<'react-infinite/build/utils/checkProps'>;
}
declare module 'react-infinite/build/utils/establish-polyfills.js' {
  declare module.exports: $Exports<'react-infinite/build/utils/establish-polyfills'>;
}
declare module 'react-infinite/build/utils/infiniteHelpers.js' {
  declare module.exports: $Exports<'react-infinite/build/utils/infiniteHelpers'>;
}
declare module 'react-infinite/build/utils/scaleEnum.js' {
  declare module.exports: $Exports<'react-infinite/build/utils/scaleEnum'>;
}
declare module 'react-infinite/build/utils/types.js' {
  declare module.exports: $Exports<'react-infinite/build/utils/types'>;
}
declare module 'react-infinite/dist/react-infinite.js' {
  declare module.exports: $Exports<'react-infinite/dist/react-infinite'>;
}
declare module 'react-infinite/dist/react-infinite.min.js' {
  declare module.exports: $Exports<'react-infinite/dist/react-infinite.min'>;
}
declare module 'react-infinite/examples/borderless-window.jsx' {
  declare module.exports: $Exports<'react-infinite/examples/borderless-window'>;
}
declare module 'react-infinite/examples/chat.jsx' {
  declare module.exports: $Exports<'react-infinite/examples/chat'>;
}
declare module 'react-infinite/examples/index.jsx' {
  declare module.exports: $Exports<'react-infinite/examples/index'>;
}
declare module 'react-infinite/examples/window.jsx' {
  declare module.exports: $Exports<'react-infinite/examples/window'>;
}
declare module 'react-infinite/Gulpfile.js' {
  declare module.exports: $Exports<'react-infinite/Gulpfile'>;
}
declare module 'react-infinite/pipeline/browserify.js' {
  declare module.exports: $Exports<'react-infinite/pipeline/browserify'>;
}
declare module 'react-infinite/src/computers/arrayInfiniteComputer.js' {
  declare module.exports: $Exports<'react-infinite/src/computers/arrayInfiniteComputer'>;
}
declare module 'react-infinite/src/computers/constantInfiniteComputer.js' {
  declare module.exports: $Exports<'react-infinite/src/computers/constantInfiniteComputer'>;
}
declare module 'react-infinite/src/computers/infiniteComputer.js' {
  declare module.exports: $Exports<'react-infinite/src/computers/infiniteComputer'>;
}
declare module 'react-infinite/src/react-infinite.jsx' {
  declare module.exports: $Exports<'react-infinite/src/react-infinite'>;
}
declare module 'react-infinite/src/utils/binaryIndexSearch.js' {
  declare module.exports: $Exports<'react-infinite/src/utils/binaryIndexSearch'>;
}
declare module 'react-infinite/src/utils/checkProps.js' {
  declare module.exports: $Exports<'react-infinite/src/utils/checkProps'>;
}
declare module 'react-infinite/src/utils/establish-polyfills.js' {
  declare module.exports: $Exports<'react-infinite/src/utils/establish-polyfills'>;
}
declare module 'react-infinite/src/utils/infiniteHelpers.js' {
  declare module.exports: $Exports<'react-infinite/src/utils/infiniteHelpers'>;
}
declare module 'react-infinite/src/utils/scaleEnum.js' {
  declare module.exports: $Exports<'react-infinite/src/utils/scaleEnum'>;
}
declare module 'react-infinite/src/utils/types.js' {
  declare module.exports: $Exports<'react-infinite/src/utils/types'>;
}
declare module 'react-infinite/typelib/component/infinite_computer_types.js' {
  declare module.exports: $Exports<'react-infinite/typelib/component/infinite_computer_types'>;
}
declare module 'react-infinite/typelib/component/react_infinite_types.js' {
  declare module.exports: $Exports<'react-infinite/typelib/component/react_infinite_types'>;
}
