// flow-typed signature: 21c9142f54e4ab5933e8967b50aebace
// flow-typed version: <<STUB>>/xss_v^0.2.12/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'xss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xss/benchmark/index' {
  declare module.exports: any;
}

declare module 'xss/benchmark/vs_validator' {
  declare module.exports: any;
}

declare module 'xss/dist/xss' {
  declare module.exports: any;
}

declare module 'xss/dist/xss.min' {
  declare module.exports: any;
}

declare module 'xss/example/allows_attr_prefix' {
  declare module.exports: any;
}

declare module 'xss/example/allows_tag_prefix' {
  declare module.exports: any;
}

declare module 'xss/example/analyse_img_list' {
  declare module.exports: any;
}

declare module 'xss/example/strip_tag' {
  declare module.exports: any;
}

declare module 'xss/lib/cli' {
  declare module.exports: any;
}

declare module 'xss/lib/default' {
  declare module.exports: any;
}

declare module 'xss/lib/index' {
  declare module.exports: any;
}

declare module 'xss/lib/parser' {
  declare module.exports: any;
}

declare module 'xss/lib/util' {
  declare module.exports: any;
}

declare module 'xss/lib/xss' {
  declare module.exports: any;
}

declare module 'xss/test/test_custom_method' {
  declare module.exports: any;
}

declare module 'xss/test/test_html_parser' {
  declare module.exports: any;
}

declare module 'xss/test/test_xss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xss/benchmark/index.js' {
  declare module.exports: $Exports<'xss/benchmark/index'>;
}
declare module 'xss/benchmark/vs_validator.js' {
  declare module.exports: $Exports<'xss/benchmark/vs_validator'>;
}
declare module 'xss/dist/xss.js' {
  declare module.exports: $Exports<'xss/dist/xss'>;
}
declare module 'xss/dist/xss.min.js' {
  declare module.exports: $Exports<'xss/dist/xss.min'>;
}
declare module 'xss/example/allows_attr_prefix.js' {
  declare module.exports: $Exports<'xss/example/allows_attr_prefix'>;
}
declare module 'xss/example/allows_tag_prefix.js' {
  declare module.exports: $Exports<'xss/example/allows_tag_prefix'>;
}
declare module 'xss/example/analyse_img_list.js' {
  declare module.exports: $Exports<'xss/example/analyse_img_list'>;
}
declare module 'xss/example/strip_tag.js' {
  declare module.exports: $Exports<'xss/example/strip_tag'>;
}
declare module 'xss/lib/cli.js' {
  declare module.exports: $Exports<'xss/lib/cli'>;
}
declare module 'xss/lib/default.js' {
  declare module.exports: $Exports<'xss/lib/default'>;
}
declare module 'xss/lib/index.js' {
  declare module.exports: $Exports<'xss/lib/index'>;
}
declare module 'xss/lib/parser.js' {
  declare module.exports: $Exports<'xss/lib/parser'>;
}
declare module 'xss/lib/util.js' {
  declare module.exports: $Exports<'xss/lib/util'>;
}
declare module 'xss/lib/xss.js' {
  declare module.exports: $Exports<'xss/lib/xss'>;
}
declare module 'xss/test/test_custom_method.js' {
  declare module.exports: $Exports<'xss/test/test_custom_method'>;
}
declare module 'xss/test/test_html_parser.js' {
  declare module.exports: $Exports<'xss/test/test_html_parser'>;
}
declare module 'xss/test/test_xss.js' {
  declare module.exports: $Exports<'xss/test/test_xss'>;
}
