/**
 * TEAM: frontend_infra
 */

/* eslint-disable  */

"use strict";

module.exports = {
  // Documented components. Found with `rg '@status'`.
  Portal: "Portal.jsx",
  Logo: "Logo.jsx",
  DeprecatedVerticalGroup: "DeprecatedVerticalGroup.jsx",
  CheckboxList: "CheckboxList.jsx",
  GraphicIcon: "GraphicIcon.jsx",
  Pill: "Pill.jsx",
  HelpTooltip: "HelpTooltip.jsx",
  InlineEdit: "InlineEdit.jsx",
  DropdownButton: "DropdownButton.jsx",
  InputError: "InputError.jsx",
  Checkbox: "Checkbox.jsx",
  TextLink: "TextLink.jsx",
  Text: "Text.jsx",
  SettingsToggle: "SettingsToggle.jsx",
  Badge: "Badge.jsx",
  Icon: "Icon.jsx",
  Flag: "Flag.jsx",
  TextInput: "TextInput.jsx",
  TextLinkAction: "TextLinkAction.jsx",
  Loader: "Loader.jsx",
  TextInputAutocomplete: "TextInputAutocomplete.jsx",
  Link: "Link.jsx",
  Banner: "Banner.jsx",
  FloatInput: "FloatInput.jsx",
  DeprecatedHorizontalGroup: "DeprecatedHorizontalGroup.jsx",
  Group: "Group.jsx",
  MultiInput: "MultiInput.jsx",
  TextareaInput: "TextareaInput.jsx",
  TabHeader: "tabs/TabHeader.jsx",
  Tabs: "tabs/Tabs.jsx",
  Drawer: "Drawer.jsx",
  Label: "Label.jsx",
  InputGroup: "InputGroup.jsx",
  FormSection: "form/FormSection.jsx",
  RadioGroup: "radio/RadioGroup.jsx",
  FormRow: "form/FormRow.jsx",
  ProgressBar: "ProgressBar.jsx",
  Radio: "radio/Radio.jsx",
  ProgressTracker: "progress/ProgressTracker.jsx",
  Toast: "toast/Toast.jsx",
  Toaster: "toast/Toaster.jsx",
  CalendarDateRange: "date/CalendarDateRange.jsx",
  CalendarDateInput: "date/CalendarDateInput.jsx",
  TimeInput: "date/TimeInput.jsx",
  PdfViewer: "document/PdfViewer.jsx",
  FileUploader: "document/FileUploader.jsx",
  DateTimeInput: "date/DateTimeInput.jsx",
  DocumentUploader: "document/DocumentUploader.jsx",
  TakeoverLoader: "takeover/TakeoverLoader.jsx",
  CustomPopover: "popover/CustomPopover.jsx",
  GeneralPopover: "popover/GeneralPopover.jsx",
  IconButton: "button/IconButton.jsx",
  Button: "button/Button.jsx",
  AnchorButton: "button/AnchorButton.jsx",
  Table: "table/Table.jsx",
  AnchorIconButton: "button/AnchorIconButton.jsx",
  SearchableSelectInput: "select/SearchableSelectInput.jsx",
  MultiselectOptions: "select/MultiselectOptions.jsx",
  MultiselectInput: "select/MultiselectInput.jsx",
  BaseReactSelect: "select/BaseReactSelect.jsx",
  DropdownList: "select/DropdownList.jsx",
  SelectInput: "select/SelectInput.jsx",
  DropdownOption: "select/DropdownOption.jsx",
  SearchableMultiselectFilter: "filter/SearchableMultiselectFilter.jsx",
  MultiselectFilter: "filter/MultiselectFilter.jsx",
  SelectFilter: "filter/SelectFilter.jsx",
  BaseFilter: "filter/BaseFilter.jsx",
  GeneralModalBody: "modal/GeneralModalBody.jsx",
  NotificationModal: "modal/NotificationModal.jsx",
  StaticGeneralModalLoader: "modal/StaticGeneralModalLoader.jsx",
  CustomModal: "modal/CustomModal.jsx",
  GeneralModalLoader: "modal/GeneralModalLoader.jsx",
  Cell: "grid/Cell.jsx",
  Row: "grid/Row.jsx",
  DateRangeFilter: "filter/DateRangeFilter.jsx",
  Grid: "grid/Grid.jsx",
  DocumentTabs: "document/DocumentTabs/DocumentTabs.jsx",
  // Secret menu! These modules don't seem to be documented but looked important
  // enough not to delete.
  CalendarDateRangeTools: "date/CalendarDateRangeTools.js",
  CalendarDateTypeTools: "date/CalendarDateTypeTools.js",
  serializeFilters: "filter/serializeFilters.js",
  FormError: "form/FormError.jsx",
  FormSectionError: "form/FormSectionError.jsx",
  Rule: "form/Rule.jsx",
  DeprecatedPopperWithArrow: "popup/DeprecatedPopperWithArrow.jsx",
  BooleanRadioGroup: "radio/BooleanRadioGroup.jsx",
  Column: "table/Column.jsx",
  LinkCell: "table/LinkCell.jsx",
  StaticTable: "table/StaticTable.jsx",
  TableRow: "table/TableRow.jsx",
};
