# Javascript Node CircleCI 2.0 configuration file
# TEAM: frontend_infra
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  jest:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run jest --maxWorkers=2

  flow:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn flow

  webpack:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn webpack

  eslint:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn eslint .

workflows:
  version: 2
  all_the_things:
    jobs:
      - jest
      - flow
      - webpack
      - eslint
